[jack]
client_name = "Synth"
audio_out_port_name = "audio_out"
midi_in_port_name = "midi_in"
system_audio_l_port_name = "system:playback_1"
system_audio_r_port_name = "system:playback_2"

[synth.stops]
"16' Subbass" = { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 0.8 }
"8' Principal" = { frequency_ratio = 1.0, waveform = "triangle", amplitude_ratio = 1.0 }
"4' Octave" = { frequency_ratio = 2.0, waveform = "triangle", amplitude_ratio = 2.0 }
"2 2/3' Fifth" = { frequency_ratio = 3.0, waveform = "triangle", amplitude_ratio = 0.6 }
"1 3/5' Tierce" = { frequency_ratio = 5.0, waveform = "triangle", amplitude_ratio = 0.4 }
"16' Flute" = { frequency_ratio = 0.5, waveform = "sine", amplitude_ratio = 0.8 }
"8' Flute" = { frequency_ratio = 1.0, waveform = "sine", amplitude_ratio = 0.6 }
"4' Flute" = { frequency_ratio = 2.0, waveform = "sine", amplitude_ratio = 0.4 }

[synth.presets.pedalboard_default]
midi_identifier = 20
stops = [
    "16' Subbass",
    "8' Principal",
]
channels = [2]
display_name = "Default"

[synth.presets.manual_default]
midi_identifier = 21
stops = [
    "8' Principal",
    "4' Octave",

]
channels = [1]
display_name = "Default"

[synth.presets.organo_pleno]
midi_identifier = 22
stops = [
    "16' Subbass",
    "8' Principal",
    "4' Octave",
]
channels = [1]
display_name = "Pleno"


[synth.presets.mixture]
midi_identifier = 23
stops = [
    "16' Subbass",
    "8' Principal",
    "4' Octave",
    "2 2/3' Fifth",
    "1 3/5' Tierce"
]
channels = [1]
display_name = "Mixture"

[synth.presets.manual_flute]
midi_identifier = 24
stops = [
    "8' Flute",
    "4' Flute"
]
channels = [1]
display_name = "Flute"

[synth.presets.pedalboard_flute]
midi_identifier = 25
stops = [
    "16' Flute",
    "8' Flute"
]
channels = [2]
display_name = "Flute"

[[synth.preset_defaults]]
midi_channel = 1
channel_name = "Manual"
preset_name = "manual_default"

[[synth.preset_defaults]]
midi_channel = 2
channel_name = "Pedalboard"
preset_name = "pedalboard_default"
