[jack]
client_name = "Synth"
audio_out_port_name = "audio_out"
midi_in_port_name = "midi_in"
system_audio_l_port_name = "system:playback_1"
system_audio_r_port_name = "system:playback_2"

[synth.reverb]
room_size = 0.85
damping = 0.5
wet = 0.35
dry = 0.65
pre_delay_ms = 20.0

[synth.stops]
"16' Subbass" = { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 0.8 }
"8' Principal" = { frequency_ratio = 1.0, waveform = "triangle", amplitude_ratio = 1.0, chiff_intensity = 0.3, chiff_duration = 0.04, attack_time = 0.03, release_time = 0.1 }
"4' Octave" = { frequency_ratio = 2.0, waveform = "triangle", amplitude_ratio = 2.0 }
"2' Super Octave" = { frequency_ratio = 4.0, waveform = "triangle", amplitude_ratio = 1.0 }
"2 2/3' Fifth" = { frequency_ratio = 3.0, waveform = "triangle", amplitude_ratio = 1.2 }
"1 3/5' Tierce" = { frequency_ratio = 5.0, waveform = "triangle", amplitude_ratio = 1.2 }
"1 1/3' Larigot" = { frequency_ratio = 6.0, waveform = "triangle", amplitude_ratio = 1.0 }
"16' Flute" = { frequency_ratio = 0.5, waveform = "sine", amplitude_ratio = 0.8, chiff_intensity = 0.1, chiff_duration = 0.05, attack_time = 0.08, release_time = 0.15 }
"8' Flute" = { frequency_ratio = 1.0, waveform = "sine", amplitude_ratio = 1.8 }
"4' Flute" = { frequency_ratio = 2.0, waveform = "sine", amplitude_ratio = 1.2 }
"16' Trumpet" = { frequency_ratio = 0.5, waveform = "trumpet", amplitude_ratio = 0.4, chiff_intensity = 0.4, chiff_duration = 0.03, attack_time = 0.01, release_time = 0.08 }
"8' Trumpet" = { frequency_ratio = 1.0, waveform = "trumpet", amplitude_ratio = 0.6 }
"4' Trumpet" = { frequency_ratio = 2.0, waveform = "trumpet", amplitude_ratio = 1.0 }


[synth.presets.pedalboard_default]
midi_identifier = 20
stops = [
    { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 1.0 },
    { frequency_ratio = 1.0, waveform = "triangle", amplitude_ratio = 2.2 },
]
channels = [2]
display_name = "Default"

[synth.presets.pedalboard_reed]
midi_identifier = 29
stops = [
    { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 0.6 },
    { frequency_ratio = 1.0, waveform = "triangle", amplitude_ratio = 1.8 },
    { frequency_ratio = 1.0, waveform = "trumpet", amplitude_ratio = 0.6 },
]
channels = [2]
display_name = "Reed"


[synth.presets.manual_default]
midi_identifier = 21
stops = [
    "8' Principal",
    "4' Octave",
]
channels = [1]
display_name = "Default"

[synth.presets.organo_pleno]
midi_identifier = 22
stops = [
    { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 0.6 },
    "8' Principal",
    { frequency_ratio = 2.0, waveform = "triangle", amplitude_ratio = 4.0 },
]
channels = [1]
display_name = "Pleno"


[synth.presets.mixture]
midi_identifier = 23
stops = [
    "8' Principal",
    "4' Octave",
    "2 2/3' Fifth",
    "1 3/5' Tierce"
]
channels = [1]
display_name = "Mixture"

[synth.presets.manual_flute]
midi_identifier = 24
stops = [
    "8' Flute",
    "4' Flute"
]
channels = [1]
display_name = "Flute"

[synth.presets.pedalboard_flute]
midi_identifier = 25
stops = [
    { frequency_ratio = 0.5, waveform = "sine", amplitude_ratio = 1.0 },
    { frequency_ratio = 1.0, waveform = "sine", amplitude_ratio = 1.6 },
]
channels = [2]
display_name = "Flute"

[synth.presets.pedalboard_trumpet]
midi_identifier = 26
stops = [
    "16' Trumpet",
    "8' Trumpet",
]
channels = [2]
display_name = "Trumpet"

[synth.presets.manual_trumpet]
midi_identifier = 27
stops = [
    "8' Trumpet",
    "4' Trumpet",
]
channels = [1]
display_name = "Trumpet"

[synth.presets.plein_jeu]
midi_identifier = 28
stops = [
    { frequency_ratio = 0.5, waveform = "triangle", amplitude_ratio = 0.6 },
    { frequency_ratio = 1.0, waveform = "triangle", amplitude_ratio = 1.0 },
    { frequency_ratio = 2.0, waveform = "triangle", amplitude_ratio = 1.4 },
    { frequency_ratio = 4.0, waveform = "triangle", amplitude_ratio = 1.6 },
    { frequency_ratio = 3.0, waveform = "triangle", amplitude_ratio = 1.8 },
    { frequency_ratio = 6.0, waveform = "triangle", amplitude_ratio = 2.0 }
]
channels = [1]
display_name = "Plein Jeu"

[[synth.preset_defaults]]
midi_channel = 1
channel_name = "Manual"
preset_name = "manual_default"

[[synth.preset_defaults]]
midi_channel = 2
channel_name = "Pedalboard"
preset_name = "pedalboard_default"
